"""empty message

Revision ID: 107f49b57635
Revises: 
Create Date: 2025-11-05 22:38:51.089938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107f49b57635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('sobrenome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contato_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_contato_usuario', sa.Integer(), nullable=False),
    sa.Column('telefone1', sa.String(length=20), nullable=False),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['fk_contato_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone1'),
    sa.UniqueConstraint('telefone2')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=30), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('fk_venda_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_venda_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda')
    op.drop_table('contato_usuario')
    op.drop_table('usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
