"""retirada do nome

Revision ID: 13d41659640e
Revises: 
Create Date: 2025-10-22 17:18:40.153214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d41659640e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('assunto', sa.String(length=50), nullable=True),
    sa.Column('menssagem', sa.String(length=50), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('resposta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contatos')
    # ### end Alembic commands ###
