"""empty message

Revision ID: 39067c42c04c
Revises: 67528e32c552
Create Date: 2025-11-06 19:25:57.716272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39067c42c04c'
down_revision = '67528e32c552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('vendedor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
