"""vendedor id

Revision ID: 67528e32c552
Revises: 107f49b57635
Create Date: 2025-11-06 18:29:47.831997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67528e32c552'
down_revision = '107f49b57635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.drop_column('vendedor_id')

    # ### end Alembic commands ###
