"""mundaça na tabela

Revision ID: f15c5b356538
Revises: 13d41659640e
Create Date: 2025-10-22 18:09:25.713325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15c5b356538'
down_revision = '13d41659640e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.String(length=50), nullable=True))
        batch_op.drop_column('menssagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menssagem', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###
